runtime: python27
# https://support.atlassian.com/bitbucket-cloud/docs/deploy-to-google-cloud/
api_version: 1
threadsafe: yes

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|woff|woff2)(|\.map))$
    static_files: dist/web-tfsp/\1
    upload: dist/web-tfsp/(.*)(|\.map)

  - url: /(.*)
    static_files: dist/web-tfsp/index.html
    upload: dist/web-tfsp/index.html

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE